// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_victory = "CgkIqO_Co4UaEAIQAQ"; // <GPGSID>
        public const string achievement_survival = "CgkIqO_Co4UaEAIQCA"; // <GPGSID>
        public const string achievement_mastery = "CgkIqO_Co4UaEAIQBg"; // <GPGSID>
        public const string achievement_achieve_completion = "CgkIqO_Co4UaEAIQCg"; // <GPGSID>
        public const string achievement_desolation = "CgkIqO_Co4UaEAIQAg"; // <GPGSID>
        public const string achievement_peak_performance = "CgkIqO_Co4UaEAIQBw"; // <GPGSID>
        public const string achievement_miracle = "CgkIqO_Co4UaEAIQBA"; // <GPGSID>
        public const string achievement_growth = "CgkIqO_Co4UaEAIQBQ"; // <GPGSID>
        public const string achievement_transcendance = "CgkIqO_Co4UaEAIQCQ"; // <GPGSID>
        public const string achievement_rest = "CgkIqO_Co4UaEAIQAw"; // <GPGSID>

}

